locs=["Liberty City","Los Santos","Vice City ","San Francisco","Gotham"]
print(locs)
print(sorted(locs))
print(locs)
print(sorted(locs,reverse=True))
#注意是True，首字母大写，表示逻辑真。true是变量
print(locs)
locs.reverse()
print(locs)
locs.reverse()
print(locs)
locs.sort()
print(locs)
locs.sort(reverse=True)
print(locs)